### PR TITLE
[Enhancement] support for shift mask keys for clip group range selection

### PR DESCRIPTION
**Pull request by HarishFulara07**
Fix for T3112 - [regression] Re-add support for shift mask keys for clip group range selection

### CODE REVIEW

**Comment by HarishFulara07** [comment]
@aleb I have made ht

**Comment by HarishFulara07** [comment]
@aleb Please review the changes. I have incorporated changes as per last added comments - https://github.com/HarishFulara07/pitivi/commit/a3a2c542b784f159490d7a3384881acc71493989

**Comment by aleb** [comment]
8 tests fail when I cherry-pick this commit on top of origin/1.0: https://gist.github.com/aleb/c21ddc39f8bc30b072eb694c6e873790

Not sure what's the best way to fix them, I did not have a close look. Saying that, maybe you can use http://lazka.github.io/pgi-docs/#Gdk-3.0/classes/Event.html#Gdk.Event.new

**Comment by aleb** [comment]
Let's move this to gitlab.gnome.org/GNOME/pitivi - I'll close this pull request.

**Pull request closed without merging**
